name: app
description: An App to manage your plants and (watering) schedules
authors:
  - Martin Wagenführ <martin@wgnf.de>
homepage: https://github.com/wgnf/plent

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2

  firebase_analytics: ^8.2.0
  intl: ^0.17.0
  localstore: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
